// http-server/go_client/web_vue/src/components/Sidebar.jsx
import { onMounted, ref, watch } from "vue"
import FileTree from "./FileTree.jsx"
import TTSSynthesizer from "./TTSSynthesizer.jsx"

const LoadingSpinner = {
  template: `
    <div class="flex flex-col items-center justify-center h-full text-slate-500">
      <div class="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-indigo-500"></div>
      <span class="mt-4 text-lg">Loading Library...</span>
    </div>
  `,
}

export default {
  props: {
    audioFilesCount: Number,
    loading: Boolean,
    fileTree: Object,
    isSynthesizing: Boolean,
    selectedFile: Object,
    currentlyPlaying: String,
  },
  emits: ["selectFile", "deleteFile", "synthesize", "pauseCurrent"],
  setup(props, { emit }) {
    const filetree_node = ref(null)

    console.log('xxxxx')
    watch(
      filetree_node,
      () => {
        if (filetree_node.value) {
          console.log(filetree_node.value.data)
        }
      },
      { immediate: true },
    ) // immediate: true to run on initial render

    return () => (
      <aside class="w-[300px] bg-white/80 backdrop-blur-lg border-r border-slate-200 flex flex-col">
        <div class="flex-1 overflow-y-auto p-2">
          {props.loading ? (
            <LoadingSpinner />
          ) : (
            <FileTree
              ref={filetree_node}
              file-tree={props.fileTree}
              onSelectFile={(event) => emit("selectFile", event)}
              onDeleteFile={(event) => emit("deleteFile", event)}
              currently-playing={props.currentlyPlaying}
              onPauseCurrent={() => emit("pauseCurrent")}
            />
          )}
        </div>
        <TTSSynthesizer
          onSynthesize={(event) => emit("synthesize", event)}
          is-synthesizing={props.isSynthesizing}
          selected-file={props.selectedFile}
        />
      </aside>
    )
  },
}

// http-server/go_client/web/src/components/Sidebar.jsx
import React from 'react'
import FileTree from './FileTree'
import TTSSynthesizer from './TTSSynthesizer' // Import the new component

const LoadingSpinner = () => (
  <div className="flex flex-col items-center justify-center h-full text-slate-500">
    <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-indigo-500"></div>
    <span className="mt-4 text-lg">Loading Library...</span>
  </div>
)

// Add onSynthesize, isSynthesizing, and selectedFile to the props
const Sidebar = ({ audioFilesCount, loading, fileTree, onSelectFile, onDeleteFile, onSynthesize, isSynthesizing, selectedFile, currentlyPlaying, onPauseCurrent }) => {
  return (
    <aside className="w-[300px] bg-white/80 backdrop-blur-lg border-r border-slate-200 flex flex-col">
      {
        // <div className="p-4 border-b border-slate-200">
        //   <h2 className="text-lg font-semibold flex items-center text-slate-800">
        //     <svg className="w-6 h-6 mr-2.5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        //       <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"></path>
        //     </svg>
        //     Audio Library
        //     <span className="ml-auto bg-indigo-100 text-indigo-800 text-xs font-medium px-2.5 py-1 rounded-full">{audioFilesCount} files</span>
        //   </h2>
        // </div>
      }
      <div className="flex-1 overflow-y-auto p-2">
        {loading ? <LoadingSpinner /> : <FileTree fileTree={fileTree} onSelectFile={onSelectFile} onDeleteFile={onDeleteFile} currentlyPlaying={currentlyPlaying} onPauseCurrent={onPauseCurrent} />}
      </div>
      {/* Add the TTS component at the bottom, passing the selectedFile prop */}
      <TTSSynthesizer onSynthesize={onSynthesize} isSynthesizing={isSynthesizing} selectedFile={selectedFile} />
    </aside>
  )
}

export default Sidebar
