// http-server/go_client/react_vite/src/App.jsx
import React, { useState, useEffect, useCallback } from 'react'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import AudioPlayer from './components/AudioPlayer'
import Footer from './components/Footer'
import { buildFileTree } from './utils/fileTree'
import './App.css'

const App = () => {
  const [audioFiles, setAudioFiles] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [fileTree, setFileTree] = useState(null)
  const [selectedFile, setSelectedFile] = useState(null)
  const [audioUrl, setAudioUrl] = useState(null)
  const [isSynthesizing, setIsSynthesizing] = useState(false)

  const fetchAudioFiles = useCallback(async () => {
    setLoading(true)
    try {
      const response = await fetch('http://localhost:8081/api/audio-files')
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }
      const data = await response.json()
      setAudioFiles(data.files || [])
      setFileTree(buildFileTree(data.files))
      setError(null)
    } catch (err) {
      setError(err.message)
      console.error('Error fetching audio files:', err)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchAudioFiles()
  }, [fetchAudioFiles])

  const handleFileSelect = (fileData) => {
    setSelectedFile(fileData)
    setAudioUrl(`http://localhost:8081${fileData.URL}`)
  }

  const handleSynthesize = useCallback(
    async (text) => {
      setIsSynthesizing(true)
      try {
        // Use the selected file's path as the speaker audio, or a default if none is selected.
        const speakerAudioPath = selectedFile ? selectedFile.Path : '/home/zdz/temp/TTS/assets/self_voice.wav'

        const requestBody = {
          text: text,
          speaker_audio_path: speakerAudioPath,
          output_wav_path: '', // The backend will generate the path
          emotion_text: 'default',
          emotion_alpha: 0.7,
          interval_silence: 500
        }

        const response = await fetch('http://localhost:8081/api/tts', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify(requestBody)
        })

        if (!response.ok) {
          const errorBody = await response.text()
          throw new Error(`TTS API error! status: ${response.status}, body: ${errorBody}`)
        }

        const result = await response.json()

        // Immediately select the new file for playback
        if (result.newFile) {
          handleFileSelect(result.newFile)
        }

        // Refresh the file list to show the new file in the sidebar
        await fetchAudioFiles()
      } catch (err) {
        console.error('Error synthesizing audio:', err)
        // Optionally, set an error state to show in the UI
      } finally {
        setIsSynthesizing(false)
      }
    },
    [fetchAudioFiles, selectedFile]
  ) // Add selectedFile to the dependency array

  const handleDeleteFile = async (filePath) => {
    try {
      const response = await fetch('http://localhost:8081/api/delete-file', {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ path: filePath })
      })

      if (!response.ok) {
        throw new Error(`Delete API error! status: ${response.status}`)
      }

      // Refresh the file list after deletion
      await fetchAudioFiles()

      // If the deleted file was currently selected, clear the selection
      if (selectedFile && selectedFile.Path === filePath) {
        setSelectedFile(null)
        setAudioUrl(null)
      }
    } catch (err) {
      console.error('Error deleting file:', err)
      setError(err.message)
    }
  }

  return (
    <div className="flex flex-col h-screen bg-slate-50 text-slate-800 cursor-default">
      {
        // <Header />
      }

      <div className="flex flex-1 overflow-hidden">
        <Sidebar
          audioFilesCount={audioFiles.length}
          loading={loading}
          error={error}
          fileTree={fileTree}
          onSelectFile={handleFileSelect}
          onDeleteFile={handleDeleteFile}
          onSynthesize={handleSynthesize}
          isSynthesizing={isSynthesizing}
          selectedFile={selectedFile} // Pass selectedFile down
        />
        <AudioPlayer selectedFile={selectedFile} audioUrl={audioUrl} />
      </div>

      <Footer />
    </div>
  )
}

export default App

// http-server/go_client/web_vue/src/App.vue
<template>
  <div class="flex flex-col h-screen bg-slate-50 text-slate-800 cursor-default">
    <div class="flex flex-1 overflow-hidden">
      <Sidebar
        :audio-files-count="audioFiles.length"
        :loading="loading"
        :file-tree="fileTree"
        @select-file="handleFileSelect"
        @delete-file="handleDeleteFile"
        @synthesize="handleSynthesize"
        :is-synthesizing="isSynthesizing"
        :selected-file="selectedFile"
        :currently-playing="currentlyPlaying"
        @pause-current="handleToggleCurrent"
      />

      <div class="flex-1 flex flex-col">
        <TextDataSettings @upload-success="fetchAudioFiles" @json-data="handleJsonData" />
        <div class="flex-1">
          <TTSList :json-data="ttsJsonData" :audio-files="audioFiles" @synthesize-complete="handleTTSListSynthesize" />
        </div>
        <div style="height: 0">
          <AudioPlayer
            :selected-file="selectedFile"
            :audio-url="audioUrl"
            @playback-complete="handlePlaybackComplete"
            @pause-requested="(callback) => (pauseCallbackRef = callback)"
          />
        </div>
      </div>
    </div>

    <Footer />
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import TextDataSettings from './components/TextDataSettings.vue'
import TTSList from './components/TTSList.vue'
import Sidebar from './components/Sidebar.vue'
import AudioPlayer from './components/AudioPlayer.vue'
import Footer from './components/Footer.vue'
import { useNotification } from './utils/notifications'
import { useAudioStore } from './stores/audio'
import { synthesizeTTS, deleteAudioFile } from './services/api/tts'

const audioStore = useAudioStore()
const {
  audioFiles,
  loading,
  fileTree,
  selectedFile,
  isSynthesizing,
  currentlyPlaying,
} = storeToRefs(audioStore)
const { fetchAudioFiles, selectFile, setSynthesizing, deleteFileSuccess } = audioStore

const { showError, showSuccess } = useNotification()

const ttsJsonData = ref(null)
const pauseCallbackRef = ref(null)

const audioUrl = computed(() => (selectedFile.value ? `http://localhost:8081${selectedFile.value.url}` : null))

onMounted(() => {
  fetchAudioFiles()
})

const handleFileSelect = (fileData) => {
  selectFile(fileData)
}

const handlePlaybackComplete = () => {
  audioStore.setCurrentlyPlaying(null)
}

const handleToggleCurrent = () => {
  if (pauseCallbackRef.value) {
    pauseCallbackRef.value()
  } else if (selectedFile.value) {
    handleFileSelect(selectedFile.value)
  }
}

const handleSynthesize = async (text) => {
  setSynthesizing(true)
  try {
    const speakerAudioPath = selectedFile.value?.path
    const result = await synthesizeTTS(text, speakerAudioPath, null)
    if (result.newFile) {
      handleFileSelect(result.newFile)
    }
    await fetchAudioFiles()
    showSuccess('Audio synthesized successfully', 'The new audio file has been created.')
  } catch (err) {
    console.error('Error synthesizing audio:', err)
    showError('Error synthesizing audio', err.message)
  } finally {
    setSynthesizing(false)
  }
}

const handleDeleteFile = async (delname) => {
  try {
    await deleteAudioFile(delname)
    deleteFileSuccess(delname)
    showSuccess('File deleted successfully', 'The file has been removed from the library.')
  } catch (err) {
    console.error('Error deleting file:', err)
    showError('Error deleting file', err.message)
  }
}

const handleJsonData = (jsonData) => {
  ttsJsonData.value = jsonData
}

const handleTTSListSynthesize = async (synthesizedFile) => {
  if (synthesizedFile) {
    handleFileSelect(synthesizedFile)
    await fetchAudioFiles()
    showSuccess('Audio synthesized successfully', 'The new audio file has been created.')
  }
}
</script>
