// http-server/go_client/web_vue/src/components/Sidebar.vue
<template>
  <aside class="w-[300px] bg-white/80 backdrop-blur-lg border-r border-slate-200 flex flex-col">
    <div class="flex-1 overflow-y-auto p-2">
      <LoadingSpinner v-if="loading" />
      <FileTree
        v-else
        :file-tree="fileTree"
        @select-file="emit('selectFile', $event)"
        @delete-file="emit('deleteFile', $event)"
        :currently-playing="currentlyPlaying"
        @pause-current="emit('pauseCurrent')"
      />
    </div>
    <TTSSynthesizer
      @synthesize="emit('synthesize', $event)"
      :is-synthesizing="isSynthesizing"
      :selected-file="selectedFile"
    />
  </aside>
</template>

<script setup>
import FileTree from './FileTree.vue'
import TTSSynthesizer from './TTSSynthesizer.vue'

const props = defineProps({
  audioFilesCount: Number,
  loading: Boolean,
  fileTree: Object,
  isSynthesizing: Boolean,
  selectedFile: Object,
  currentlyPlaying: String,
})

const emit = defineEmits(['selectFile', 'deleteFile', 'synthesize', 'pauseCurrent'])

const LoadingSpinner = {
  template: `
    <div class="flex flex-col items-center justify-center h-full text-slate-500">
      <div class="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-indigo-500"></div>
      <span class="mt-4 text-lg">Loading Library...</span>
    </div>
  `,
}
</script>

// http-server/go_client/react_vite/src/components/Sidebar.jsx
import React from 'react';
import FileTree from './FileTree';
import TtsSynthesizer from './TtsSynthesizer'; // Import the new component

const LoadingSpinner = () => (
  <div className="flex flex-col items-center justify-center h-full text-slate-500">
    <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-indigo-500"></div>
    <span className="mt-4 text-lg">Loading Library...</span>
  </div>
);

const ErrorDisplay = ({ error }) => (
  <div className="m-2 bg-red-100 border border-red-300 text-red-800 px-4 py-3 rounded-lg text-sm">
    <p className="font-bold">Error loading files</p>
    <p className="mt-1">{error}</p>
    <p className="mt-1">Please ensure the Go API server is running on port 8081.</p>
  </div>
);

// Add onSynthesize, isSynthesizing, and selectedFile to the props
const Sidebar = ({ audioFilesCount, loading, error, fileTree, onSelectFile, onSynthesize, isSynthesizing, selectedFile }) => {
  return (
    <aside className="w-[300px] bg-white/80 backdrop-blur-lg border-r border-slate-200 flex flex-col">
      <div className="p-4 border-b border-slate-200">
        <h2 className="text-lg font-semibold flex items-center text-slate-800">
          <svg className="w-6 h-6 mr-2.5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"></path></svg>
          Audio Library
          <span className="ml-auto bg-indigo-100 text-indigo-800 text-xs font-medium px-2.5 py-1 rounded-full">
            {audioFilesCount} files
          </span>
        </h2>
      </div>
      <div className="flex-1 overflow-y-auto p-2">
        {loading ? (
          <LoadingSpinner />
        ) : error ? (
          <ErrorDisplay error={error} />
        ) : (
          <FileTree fileTree={fileTree} onSelectFile={onSelectFile} />
        )}
      </div>
      {/* Add the TTS component at the bottom, passing the selectedFile prop */}
      <TtsSynthesizer onSynthesize={onSynthesize} isSynthesizing={isSynthesizing} selectedFile={selectedFile} />
    </aside>
  );
};

export default Sidebar;
